
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_databricks1'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_databricks'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  dbt_daabricks1:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: view
    
    # All models under models/bronze/ will go cleanly into 'bronze_cst' as tables
    bronze:
      +schema: bronze
      +materialized: table

seeds:
  dbt_daabricks1:
    # If you have a custom folder inside your seeds directory later, you can add its config here.
    # To force seeds into the bronze_cst schema safely, use this:
    +schema: staging