dbt_databricks:
  outputs:
    dev:
      catalog: docker_dbt
      host: HOST
      http_path: /sql/1.0/warehouses/26f3371fce5bc4a2
      schema: staging
      threads: 1
      token: TOKEN
      type: databricks
  target: dev
